theme: jekyll-theme-cayman
title: Xudong Li
description: Professor of Biomaterials  
National Engineering Research Center for Biomaterials  
Engineering Research Center in Biomaterials  
Sichuan University  
Chengdu 610064  
P R China

