theme: jekyll-theme-minimal
title: 李旭东 Xudong Li
description: 博士，生物材料教授 PhD, Professor of Biomaterials
logo: https://i1.rgstatic.net/ii/profile.image/272961781366786-1442090568134_Q128/Xudong_Li4.jpg
