theme: jekyll-theme-minimal
title: 李旭东 Xudong Li
description: 博士，生物材料教授 PhD, Professor of Biomaterials
logo: [https://github.com/xli20004/xli20004.github.io/blob/master/images/WechatIMG3711.jpeg?raw=true]
