theme: jekyll-theme-cayman
title: 欢迎来到李旭东教授的个人主页！
description: 
Position:	Professor of Biomaterials
Tel:		  +86 28 8541 2102
Fax:		  +86 28 8541 0246
Location:	Room 705, biomaterials building,
          National Engineering Research Center for Biomaterials
	     	  Engineering Research Center in Biomaterials
          Sichuan University
          Chengdu 610064
          P R China
Email:	xli20004@yahoo.com 
