theme: jekyll-theme-minimal
title: Xudong Li 李旭东
description: Professor of Biomaterials，Sichuan University 四川大学教授

Room 705, biomaterials building,  
National Engineering Research Center for Biomaterials  
Engineering Research Center in Biomaterials  
Sichuan University  
Chengdu 610064  
P R China  

Tel: +86 28 8541 2102  
Fax: +86 28 8541 0246  
Email: xli20004@yahoo.com
